# Generated by Django 5.0.1 on 2024-02-03 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('small_description', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=300)),
                ('category', models.IntegerField()),
                ('active', models.IntegerField(default=1)),
                ('is_deleted', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('uid', models.IntegerField(default=0)),
            ],
        ),
    ]
